ALTER TABLE accounts ADD COLUMN user_id TEXT NOT NULL DEFAULT '';
ALTER TABLE categories ADD COLUMN user_id TEXT NOT NULL DEFAULT '';
ALTER TABLE transactions ADD COLUMN user_id TEXT NOT NULL DEFAULT '';
